services:
  - type: web
    name: eternixai-university
    env: node
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: NEXT_PUBLIC_APP_URL
        fromService:
          name: eternixai-university
          type: web
          property: url
      - key: MONGODB_URI
        sync: false
      - key: NEXTAUTH_URL
        fromService:
          name: eternixai-university
          type: web
          property: url
      - key: NEXTAUTH_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GITHUB_ID
        sync: false
      - key: GITHUB_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
        sync: false 